name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-latest

    steps:
    # Check out repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Create env file
      working-directory: ./server
      run: echo "JWT_SECRET_KEY=D4fg0Eg6pk" >> .env
  
    # Install dependencies and run app tests
    - name: Setup server
      working-directory: ./server
      run: |
        npm ci

    - name: Setup socket
      working-directory: ./socket
      run: |
        npm ci

    - name: setup client
      working-directory: ./client
      run: |
        npm ci
        npm run start:test 
        'npx wait-on --timeout 5000 http://localhost:3000'
        'npx wait-on --timeout 5000 http://localhost:3020'
        'npx wait-on --timeout 5000 http://localhost:5173'
  
    - name: install playwright browser
      working-directory: ./client
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./client
      run: npx playwright test --reporter=line

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
